### ISSUE TITLE
Exception bug

### ISSUE THREAD

**Issue by lightless233** [lightless233/BotIzumiNg#1]
[2020-05-01 11:50:03,429] [ERROR] [ConfigParser:49] No config file find, generate a new config file 'izumi-config.yml', please edit it first! exit...
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.file.Files.writeString(Ljava/nio/file/Path;Ljava/lang/CharSequence;[Ljava/nio/file/OpenOption;)Ljava/nio/file/Path;
        at me.lightless.bot.config.ConfigParser.parseExternalConfig(ConfigParser.kt:51)
        at me.lightless.bot.MainAppKt$main$1.invokeSuspend(MainApp.kt:45)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at me.lightless.bot.MainAppKt.main(MainApp.kt:33)
        at me.lightless.bot.MainAppKt.main(MainApp.kt)

**Comment by lightless233** [comment]
Update JDK above 11
